import Head from "next/head";
import { Inter } from "next/font/google";
import classes from "@component/styles/Home.module.scss";
import Header from "@component/components/Navbar";
import Image from "next/image";
import user from "../images/bimg.png";
import Sliderr from "@component/components/Slider";
import Js from "../images/icons8-javascript.gif";
import Footer from "@component/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const skillsImg = [
  {
    id: 1,
    img: Js,
    txt: "Javascript",
  },
  {
    id: 2,
    img: Js,
    txt: "Robotics",
  },
  {
    id: 3,
    img: Js,
    txt: "Cyber Security",
  },
  {
    id: 4,
    img: Js,
    txt: "Reactjs",
  },
  {
    id: 5,
    img: Js,
    txt: "Angular",
  },
  {
    id: 6,
    img: Js,
    txt: "Python",
  },
  {
    id: 7,
    img: Js,
    txt: "Vuejs",
  },
  {
    id: 8,
    img: Js,
    txt: "Php",
  },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        {/* header */}
        <Header />
        {/* banner */}
        <div className={classes.banner_wrapper}>
          <div className={classes.container}>
            <div className={classes.inner_wrapper}>
              <div className={classes.txt_wrapper}>
                <p className={classes.big_txt}>
                  Talent management <span>Discover yourself with us!</span>
                </p>
                <p>
                  Monotonectally synthesize synergistic portals and value-add
                  paradigms. Appropriately syndicate vertical content whereas.{" "}
                </p>
                <button>Test yourself</button>
              </div>

              <Image src={user} alt="" />
            </div>
          </div>
        </div>
        {/* slider */}
        <Sliderr />
        {/* hire section  */}
        <div className={classes.hire_section}>
          <div className={classes.container}>
            <div className={classes.inner_div}>
              <h2>Hire</h2>
              <input type="text" placeholder="Search skill" />
              <p>or Choose ...</p>
              <div className={classes.skills}>
                {skillsImg.map((item, id) => (
                  <div className={classes.skill_item} key={id}>
                    <Image src={item.img} alt="" width={50} height={50} />
                    <p>{item.txt}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        {/* contact us */}
        <div className={classes.contact_bg}>
          <div className={classes.container}>
            <div className={classes.contact_wrapper}>
              <form action="">
              <h2>Contact us !</h2>
              <input type="text" placeholder="Name"/>
              <input type="text" placeholder="+998"/>
              <textarea name="msg" id="msg" cols="30" rows="2 " placeholder="Tell us about yourself"/>
              <button type="submit">Send</button>
              </form>
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2797661.0378391515!2d5.583697643324111!3d46.78281402301285!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478c64ef6f596d61%3A0x5c56b5110fcb7b15!2sSwitzerland!5e0!3m2!1sen!2s!4v1683396532508!5m2!1sen!2s" width="600" height="520" style={{border:0}} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            
          </div>
        </div>
        <Footer/>
      </main>
    </>
  );
}
